version: '3.6'
services:
  db:
    image: 'postgres:alpine3.15'
    restart: always
    ports:
    - 55432:5432
    environment:
      POSTGRES_PASSWORD: example
      DATABASE_URL: postgres://postgres@db
    volumes:
        - ./db-data:/var/lib/postgresql/data
  turnero-web:
    stdin_open: true # Enables debugging capabilities when attached to this container.
    tty: true # Enables debugging capabilities when attached to this container.
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    command: puma
    ports:
    - 30000:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=turnero
      - SKIP_DB_SETUP=true
    depends_on:
      - db
